### ISSUE TITLE
rootのbuild.gradle

### ISSUE THREAD

**Issue by RyujiOdaJP** [arsaga-partners/AndroidArchitectureTemplate#106]
# 提案したい機能
## 参考URL(記事やGithub、動画のURL)
-

## (あれば)自分のプルリクエストURL

<br>

***
<br>

# わからない実装の質問
build.gradle.ktsにすると、android{}がundefinedになるからGroovyのままなんですか？

あとsubProjectでプロジェクト跨るロジックを共有するのは非推奨とあるのが気になります。 
> [A], discouraged, way to share build logic between subproject is cross project configuration via the subprojects {} and allprojects {} DSL constructs.

[Gradle Docs: Sharing Build Logic between Subprojects](https://docs.gradle.org/current/userguide/sharing_build_logic_between_subprojects.html#sec:convention_plugins_vs_cross_configuration)

**Comment by Masaki-U** [comment]
android{}のスコープが出てこないからで合ってますね。
buildscriptの方でも良い感じに共通化する型が出てこなかったので諦めました。

**Comment by Masaki-U** [comment]
非推奨の件は初めて知りましたが、他のとこに書くとdependabotが動かなくなるので仕方なかった気がしますね。
今はRenovateなどの他の仕組みでライブラリ更新チェックするものも出てきてるので検証する価値はあるかもしれません。

**Comment by RyujiOdaJP** [comment]
> dependabotが動かなくなる
このためにBildSrcだけじゃなくroot gradle.gradleにもextバージョン書いてあるんですね
