### ISSUE TITLE
[2021/11/25][小田]

### ISSUE THREAD

**Issue by RyujiOdaJP** [arsaga-partners/AndroidArchitectureTemplate#42]
# 提案したい機能

TestでIssueを立てた。
まずこのPublicTemplateという機能について何かをサクッと調べてみた。

GitHubのTemplate Repositoryとは？
あるリポジトリのコードベースをそっくりそのまま新規のリポジトリ作成で利用できる機能です。
「え、それってforkと違うの？」っと思った方もいるかもですが、以下の点でforkとは異なります。

+ 1つのリポジトリから複数作成できる（forkだと、同名のリポジトリとなるので1人のユーザー内で複数作成は不可）
+ 元となったリポジトリのコミット履歴を継承せず、クリーンな状態でスタートできる

## 参考URL(記事やGithub、動画のURL)

- https://qiita.com/ryo2132/items/08f0561804c798012146

## (あれば)自分のプルリクエストURL

<br>

***
<br>

# わからない実装の質問
1. このPublic Templateは何をもとに作られている？
2.  Gradleいまだによく分からず雰囲気で使ってるんですが、なにか参考にしたものはありますか？トップレベルにあったり、モジュールごとに何か宣言してたり、taskなんちゃら～みたいなのとか…
3. UCSのアーキテクチャ構造と比較してどこが改善されましたか？

**Comment by Masaki-U** [comment]
Answer

1. 1からオリジナルです
2. 公式ドキュメント
3. 機能ごとにモジュールの分割をしたのと、gradleがktsになりモジュール自動生成の機能を追加したこと、CleanArchitectureを採用したこと

**Comment by Masaki-U** [comment]
Resolve
