### ISSUE TITLE
2022/1/20 久保成迪

### ISSUE THREAD

**Issue by narumichi0710** [arsaga-partners/AndroidArchitectureTemplate#58]
# 提案したい機能
DIツール使って開発してみたい
## 参考URL(記事やGithub、動画のURL)
- https://github.com/narumichi0710/githubSearchApiSample/blob/main/app/src/main/java/com/narumichi/githubsearchapisample/di/AppModule.kt

## (あれば)自分のプルリクエストURL

<br>

***
<br>

# わからない実装の質問
1.

**Comment by Masaki-U** [comment]
現状ライブラリは入っているので実装したければできる状態。
使うとしたらドメイン層は自動でDIPを満たすのでAPI周りになるかと思われます。
